[all]
10.0.1.100 ansible_user=root

[xen]
10.200.200.10
10.200.200.20

[debian_prod]
srv-prod-1 ansible_host=10.0.1.139 ansible_user=user

[ubuntu_server]
ubuntu-prod-1 ansible_host=192.168.178.33 ansible_user=user

[ceph_nodes]
ceph-node-1 ansible_host=192.168.122.4
ceph-node-2 ansible_host=192.168.122.99
ceph-node-3 ansible_host=192.168.122.125

[admin_node]
ceph-node-1

[xen:vars]
ansible_user=root

[ceph_nodes:vars]
ansible_user=user