---
- name: Update server
  hosts: ceph_nodes
  become: true
  
  tasks:
    - name: Update apt cache and perform dist-upgrade
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes