- name: Setup Fail2Ban
  hosts: vps
  become: yes
  tasks:
    - name: Ensure Fail2Ban is installed
      apt:
        name: fail2ban
        state: present
        update_cache: yes
    
    - name: Configure Fail2Ban Global Defaults
      template:
        src: templates/defaults.local.j2
        dest: /etc/fail2ban/jail.d/defaults.local
      notify: Restart Fail2Ban

    - name: Configure SSH Jail
      template:
        src: templates/sshd.local.j2
        dest: /etc/fail2ban/jail.d/sshd.local
      notify: Restart Fail2Ban

  handlers:
    - name: Restart Fail2Ban
      service:
        name: fail2ban
        state: restarted