---
- name: Setup Secure Minecraft Paper Server
  hosts: vps
  become: yes
  vars:
    mc_user: "user"
    mc_path: "/home/{{ mc_user }}/mc"
    ssh_port: 38274
    mc_port: 25565
    java_version: "openjdk-25-jre-headless"

  tasks:
    - name: Install needed packages
      apt:
        name:
          - "{{ java_version }}"
          - ufw
          - fail2ban
          - screen
        state: present
        update_cache: yes

    - name: UFW - Allow minecraft port
      ufw:
        rule: allow
        port: "{{ mc_port }}"
        proto: tcp

    - name: Create directory
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ mc_user }}"
        group: "{{ mc_user }}"
      loop:
        - "{{ mc_path }}"

    # --- Fail2Ban for minecraft port---

    - name: Check if fail2ban is installed
      ansible.builtin.service_facts:

    - name: Notify in case of fail2ban is not installed
      ansible.builtin.debug:
        msg: "NOTE: fail2ban is not installed, minecraft config is skipped!"
      when: "'fail2ban' not in ansible_facts.services"

    - name: Fail2ban Filter Configuration
      template:
        src: templates/minecraft_filter.conf.j2
        dest: /etc/fail2ban/filter.d/minecraft.conf
      notify: restart fail2ban

    - name: Fail2ban Jail Configuration
      template:
        src: templates/minecraft_jail.local.j2
        dest: /etc/fail2ban/jail.d/minecraft.local
      notify: restart fail2ban

  handlers:
    - name: restart fail2ban
      service:
        name: fail2ban
        state: restarted